# Generated by Django 3.2.18 on 2023-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
